### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by wangqi1379** [Nyloner/NyPython#1]
请问您这个验证码的字模库，是怎么建立的？

**Comment by Nyloner** [comment]
先获取一部分图片，将字符切割出来，手动分类的

**Comment by wangqi1379** [comment]
图片我已获取了一部分，我该怎么切割那？是手动切割吗？

**Comment by Nyloner** [comment]
代码里面有切割的函数cut_image

**Comment by wangqi1379** [comment]
能加一下您的qq吗？刚接触这个，想详细请教您

**Comment by wangqi1379** [comment]
http://www.chinawutong.com/login.html?url=http://www.chinawutong.com/
你能帮我看下这个网址的登录验证码，能被解析出来吗？

**Comment by wangqi1379** [comment]
好的，谢谢，切割函数最后返回的就是切割好的图片吗？

**Comment by wangqi1379** [comment]
干扰线与噪点以去掉，我要手动切割，保存成字模吗？

**Comment by wangqi1379** [comment]
还是说，我只要手动去除噪点与干扰线，就可以用cut_image切割成字模那？我该怎么保存那？

**Comment by Nyloner** [comment]
你看源码啊

**Comment by Nyloner** [comment]
你先把代码看懂，识别的过程是转成灰度图，去噪，切割，再对切割后的每个字符做识别。cut_image传入的是处理后Image对象，对图像按空白部分切割，返回切割后的图像列表。要保存的话，Image对象有save方法，你遍历一遍返回的图像列表，将每个对象保存就好。

**Comment by wangqi1379** [comment]
![1](https://cloud.githubusercontent.com/assets/22285221/19757538/f92c2166-9c55-11e6-8f5f-fd3ffa3622c6.jpeg)

**Comment by wangqi1379** [comment]
这种无法切割并识别啊

**Comment by wangqi1379** [comment]
这种情况，我手动切割的话，程序会识别吗

**Comment by wangqi1379** [comment]
我手动切割就会报错
Traceback (most recent call last):
  File "F:/nypython/NyPython-master/CaptchaRecognise/recognise.py", line 118, in <module>
    result=imageRecognize.recognise(image)
  File "F:/nypython/NyPython-master/CaptchaRecognise/recognise.py", line 106, in recognise
    relevance+=self.relation(vector,img)
  File "F:/nypython/NyPython-master/CaptchaRecognise/recognise.py", line 89, in relation
    topvalue += count * concordance2[word]
TypeError: unsupported operand type(s) for +=: 'int' and 'tuple'

**Comment by wangqi1379** [comment]
![11](https://cloud.githubusercontent.com/assets/22285221/19760882/441c8408-9c66-11e6-802c-91be7e60e113.jpeg)
