### ISSUE TITLE
word cute 运行出错

### ISSUE THREAD

**Issue by makeyoyo** [Nyloner/NyPython#2]
新手请教下 运行ui_cutword.py出现以下错误

Traceback (most recent call last):
  File "ui_cutword.py", line 140, in <module>
    cutword=Cutword()
  File "ui_cutword.py", line 89, in __init__
    super(Participle,self).__init__()
NameError: name 'Participle' is not defined

版本
jieba (0.38)
openpyxl (2.4.7)
pip (9.0.1)
PyQt5 (5.8.2)
requests (2.13.0)
setuptools (28.8.0)
sip (4.19.2)

**Comment by Nyloner** [comment]
抱歉，有一点错误，已经修改了。这个小程序没有写完，需要分词的话，直接用jieba就可以了。

**Comment by makeyoyo** [comment]
感谢，分词和统计词频用~
